PREFIX :      <http://www.cattid.uniroma1.it/2012/pampers#>
PREFIX xml:   <http://www.swows.org/xml#>
PREFIX xsd:   <http://www.w3.org/2001/XMLSchema#>
PREFIX swi:   <http://www.swows.org/instance#>
PREFIX rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:   <http://www.w3.org/2000/01/rdf-schema#>
PREFIX time:   <http://www.swows.org/time#>

CONSTRUCT {
  swi:GraphRoot
    :pacchi :Pacchi .
  :Pacchi
    :pacco ?pacco_fermo .
  ?pacco_fermo :id ?id_box .
  ?pacco_fermo :x ?x0 .
  ?pacco_fermo :y ?y0 .
}
WHERE {
  swi:GraphRoot :numPacchi ?numPacchi .
  GRAPH :boxesStartingData {
    ?box
      :id ?id_box ;
      :startPosX ?x0 ;
      :startPosY ?y0 ;
      :startSpeedX ?vx ;
      :startSpeedY ?vy .
  } .
  FILTER( ?id_box <= ?numPacchi ). 
  BIND( URI( CONCAT( STR(:pacco_fermo_), MD5(STR(?id_box)) ) ) AS ?pacco_fermo ) .
}

