PREFIX :      <http://www.cattid.uniroma1.it/2012/pampers#>
PREFIX xml:   <http://www.swows.org/xml#>
PREFIX xsd:   <http://www.w3.org/2001/XMLSchema#>
PREFIX swi:   <http://www.swows.org/instance#>
PREFIX rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:   <http://www.w3.org/2000/01/rdf-schema#>
PREFIX time:   <http://www.swows.org/time#>
PREFIX tuio:  <http://www.swows.org/tuio#>

DELETE {
  ?pallet :pacco ?flyingBox .
  ?flyingBox
    :id ?id_box ;
    :startTime ?startTime ;
    :endTime ?endTime .
}
WHERE {
  GRAPH swi:ThisGraph {
    swi:GraphRoot
      :pallet ?pallet .
    ?pallet
      :id ?palletId ;
      :pacco ?flyingBox .
    ?flyingBox
      :id ?id_box ;
      :startTime ?startTime ;
      :endTime ?endTime .
  } .
  GRAPH swi:AddedGraph {
    tuio:defaultSource tuio:updateTime ?systemTime
  } .
  FILTER( ?systemTime > ?endTime ). 
}

