PREFIX :      <http://www.cattid.uniroma1.it/2012/pampers#>
PREFIX xml:   <http://www.swows.org/xml#>
PREFIX xsd:   <http://www.w3.org/2001/XMLSchema#>
PREFIX swi:   <http://www.swows.org/instance#>
PREFIX rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:   <http://www.w3.org/2000/01/rdf-schema#>

CONSTRUCT {
  swi:GraphRoot
    :posIndicatore ?posIndicatore ;
    :numeroVisualizzato ?numeroVisualizzato .
}
WHERE {
  swi:GraphRoot :numPacchi ?numPacchi .
  BIND( ?numPacchi AS ?posIndicatore ) .
  BIND( ?numPacchi AS ?numeroVisualizzato ) .
}

