PREFIX :      <http://www.cattid.uniroma1.it/2012/pampers#>
PREFIX xsd:   <http://www.w3.org/2001/XMLSchema#>
PREFIX swi:   <http://www.swows.org/instance#>
PREFIX spinx: <http://www.swows.org/spinx#>

CONSTRUCT {
  swi:GraphRoot
    spinx:intervalStart "1"^^xsd:integer ;
    spinx:intervalEnd ?max_pacchi .
}
WHERE {
  swi:GraphRoot :maxPacchi ?max_pacchi ;
}

