PREFIX :      <http://www.cattid.uniroma1.it/2012/pampers#>
PREFIX xml:   <http://www.swows.org/xml#>
PREFIX doc:   <http://www.swows.org/xml/instance#>
PREFIX xsd:   <http://www.w3.org/2001/XMLSchema#>
PREFIX swi:   <http://www.swows.org/instance#>
PREFIX rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX dir:   </home/miguel/pampers3/dataflow/test_query_svg/>

CONSTRUCT {
  doc:page_Pallet xml:hasAttribute <#style_hidden> .
  doc:page_Home xml:hasAttribute <#style_hidden> .
  <#style_hidden>
    a xml:Attr ;
    xml:nodeName "style"^^xsd:string ;
    xml:nodeValue "{ display:none }"^^xsd:string .
}
WHERE {
  swi:GraphRoot :selectedPage ?palletPage .
  ?palletPage a :Intro . 
}

