PREFIX :      <http://www.cattid.uniroma1.it/2012/pampers#>
PREFIX xml:   <http://www.swows.org/xml#>
PREFIX doc:   <http://www.swows.org/xml/instance#>
PREFIX xsd:   <http://www.w3.org/2001/XMLSchema#>
PREFIX swi:   <http://www.swows.org/instance#>
PREFIX rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:   <http://www.w3.org/2000/01/rdf-schema#>

CONSTRUCT {
  ?layer xml:nextSibling ?next_layer .
}
WHERE {
  swi:GraphRoot rdfs:member ?num_layer .
  BIND( URI( CONCAT( STR(:layer_), MD5(STR(?num_layer)) ) ) AS ?layer ) .
  BIND( IF ( FLOOR(?num_layer / 2) = ?num_layer / 2, ?num_layer - 1, ?num_layer + 3 ) AS ?num_next_layer ) .
  FILTER( ?num_next_layer <= 32 ).
  BIND( URI( CONCAT( STR(:layer), "_", MD5(STR(?num_next_layer)) ) ) AS ?next_layer ) .
}

